#!/usr/bin/make -f
NAME = StudioGraphicEQ
FILES_DSP = StudioGraphicEq_dsp.cpp
FILES_UI  = StudioGraphicEq_ui.cpp
DPF_PATH ?= ../DPF
include $(DPF_PATH)/Makefile.plugins.mk
TARGETS += vst3
all: $(TARGETS)
